### ISSUE TITLE
Configparser error after 2to3 conversion

### ISSUE THREAD

**Issue by johnnyeaton** [drewfustin/isocronut#10]
Hi Drew,

I was really hoping to get this working, as it looks like a great solution. Alas, after much trial and error and small adjustments to get this running with Python 3.7, I have hit a wall:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Python37-32\Scripts\isocronut.py", line 393, in generate_isochrone_map
    origin_geocode = geocode_address(origin, access_type, config_path)
  File "C:\Program Files (x86)\Python37-32\Scripts\isocronut.py", line 170, in geocode_address
    key = config.get('api', 'api_number')
  File "C:\Program Files (x86)\Python37-32\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Program Files (x86)\Python37-32\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'api'`

Any ideas what's going on there? I'm stumped.

All the best,
Johnny

**Comment by syphax** [comment]
Hi Johnny,
Do you have an `[api]' header in your config file?
I am in the process of doing the 2-to-3 conversion as well. I _think_ I have it working.

**Comment by zeluspudding** [comment]
Hi @syphax , did you manage to get the Python 3 version of this working? Am facing the same struggle :/

**Comment by syphax** [comment]
I think a teammate of mine (who has since left my company) did get it working. It's been awhile; I'll have to poke around our codebase.

**Comment by zeluspudding** [comment]
Yeah, if that's something you could share that would be swell :) would definitely save me the re-work

**Comment by zeluspudding** [comment]
Any luck finding the conversion @syphax ?
